name: PetsPlus
main: net.danh.petsplus.PetsPlus
authors: [VoChiDanh]
version: "${project.version}"
description: Interactive pets for your players
api-version: 1.13
commands:
  pets:
    description: The main command for PetsPlus.
    aliases: [ petsplus ]
