name: PetsPlus
main: net.danh.petsplus.PetsPlus
author: MisterMel
version: 1.5.2
description: Interactive pets for your players
api-version: 1.13
commands:
  pets:
    description: The main command for PetsPlus.
    aliases: [ petsplus ]
