title: PreCraftingGUI
size: 1
crafting:
  kbw:
    condition:
      - "MMOCORE;CLASS;WARRIOR;1"
    ingredient: "x-b-x;x-b-x;x-a-x"
    item:
      x: AIR
      b: MMOITEMS;MATERIAL;MANHVO
      a: MMOITEMS;MATERIAL;GAY
    result: MMOITEMS;KIEM;1
    slot: 0
  gbw:
    condition:
      - "MMOCORE;CLASS;MAGE;1"
    ingredient: "x-b-x;x-b-x;x-a-x"
    item:
      x: AIR
      b: MMOITEMS;MATERIAL;MANHVO
      a: MMOITEMS;MATERIAL;GAY
    result: MMOITEMS;GAYPHEP;1
    slot: 0